### ISSUE TITLE
createServer is not exported by "__vite-browser-external"

### ISSUE THREAD

**Issue by Oynowan** [akashKarmakar02/django-vue-inertia-starter#1]
Hi, 

i cloned you project and tried to build it. Unfortunately i am getting an error. Didn't change anything. Just cloned and ran npm run build. Do you know how to fix it? 
![image](https://github.com/akashKarmakar02/django-vue-inertia-starter/assets/44809035/3dfacb15-6ec0-466b-9d55-90f7d076cc5c)

**Comment by akashKarmakar02** [comment]
I fixed that bug just now
Now Try cloning this repo and run 
`npm i`
`npm run build`
